<?php

namespace Database\Seeders;

use App\Models\PaymentMethod;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PaymentMethodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dataPaymentMethods = $this->dataPayments();
        foreach($dataPaymentMethods as $paymentMethod) {

            PaymentMethod::create($paymentMethod);

        }
    }

    public function dataPayments(): array
    {
        $dataPayments = [
            [
                'name' => 'QRIS',
                'code' => 'QRIS',
                'type' => 'QR_CODE',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'qris/qris-logo.png',
                'action' => 'qrcode',
                'min' => 10000,
                'max' => 10000000,
                'fee_type_1' => '%',
                'fee_value_1' => 1,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => false,
                'expired' => 2880,
                'payment_process' => 'instant',
                'settlement' => 2,
            ],
            [
                'name' => 'OVO',
                'code' => 'OVO',
                'type' => 'EWALLET',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'ewallet/logo-ovo.png',
                'action' => 'url',
                'min' => 10000,
                'max' => 2000000,
                'fee_type_1' => '%',
                'fee_value_1' => 2,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 1,
                'payment_process' => 'instant',
                'settlement' => 2,

            ],
            [
                'name' => 'DANA',
                'code' => 'DANA',
                'type' => 'EWALLET',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'ewallet/logo-dana.png',
                'action' => 'url',
                'min' => 10000,
                'max' => 2000000,
                'fee_type_1' => '%',
                'fee_value_1' => 2,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 5,
                'payment_process' => 'instant',
                'settlement' => 2,
            ],
            [
                'name' => 'LinkAja',
                'code' => 'LINKAJA',
                'type' => 'EWALLET',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'ewallet/logo-linkaja.png',
                'action' => 'url',
                'min' => 10000,
                'max' => 2000000,
                'fee_type_1' => '%',
                'fee_value_1' => 2,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 2880,
                'payment_process' => 'instant',
                'settlement' => 2,
            ],
            [
                'name' => 'Shopeepay',
                'code' => 'SHOPEEPAY',
                'type' => 'EWALLET',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'ewallet/logo-shopeepay.png',
                'action' => 'url',
                'min' => 10000,
                'max' => 2000000,
                'fee_type_1' => '%',
                'fee_value_1' => 2.5,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 30,
                'payment_process' => 'instant',
                'settlement' => 2,
            ],
            [
                'name' => 'AstraPay',
                'code' => 'ASTRAPAY',
                'type' => 'EWALLET',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'ewallet/logo-astrapay.png',
                'action' => 'url',
                'min' => 10000,
                'max' => 2000000,
                'fee_type_1' => '%',
                'fee_value_1' => 2,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 15,
                'payment_process' => 'instant',
                'settlement' => 2,
            ],
            [
                'name' => 'Bank Central Asia',
                'code' => 'BCA',
                'type' => 'VIRTUAL_ACCOUNT',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'VA/BCA.png',
                'action' => 'account',
                'min' => 10000,
                'max' => 50000000,
                'fee_type_1' => 'amount',
                'fee_value_1' => 4500,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 15,
                'payment_process' => 'instant',
                'settlement' => 1,
            ],
            [
                'name' => 'Bank Negara Indonesia',
                'code' => 'BNI',
                'type' => 'VIRTUAL_ACCOUNT',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'VA/BNI.png',
                'action' => 'account',
                'min' => 10000,
                'max' => 5000000000,
                'fee_type_1' => 'amount',
                'fee_value_1' => 4500,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 15,
                'payment_process' => 'instant',
                'settlement' => 0,
            ],
            [
                'name' => 'Bank Rakyat Indonesia',
                'code' => 'BRI',
                'type' => 'VIRTUAL_ACCOUNT',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'VA/BRI.png',
                'action' => 'account',
                'min' => 10000,
                'max' => 10000000,
                'fee_type_1' => 'amount',
                'fee_value_1' => 4500,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 15,
                'payment_process' => 'instant',
                'settlement' => 0,
            ],
            [
                'name' => 'Bank Mandiri',
                'code' => 'MANDIRI',
                'type' => 'VIRTUAL_ACCOUNT',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'VA/MANDIRI.png',
                'action' => 'account',
                'min' => 10000,
                'max' => 5000000000,
                'fee_type_1' => 'amount',
                'fee_value_1' => 5000,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 15,
                'payment_process' => 'instant',
                'settlement' => 0,
            ],
            [
                'name' => 'Cimb Niaga',
                'code' => 'CIMB',
                'type' => 'VIRTUAL_ACCOUNT',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'VA/CIMB.png',
                'action' => 'account',
                'min' => 10000,
                'max' => 50000000,
                'fee_type_1' => 'amount',
                'fee_value_1' => 4500,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 15,
                'payment_process' => 'instant',
                'settlement' => 0,
            ],
            [
                'name' => 'Bank Syariah Indonesia',
                'code' => 'BSI',
                'type' => 'VIRTUAL_ACCOUNT',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'VA/BSI.png',
                'action' => 'account',
                'min' => 10000,
                'max' => 5000000000,
                'fee_type_1' => 'amount',
                'fee_value_1' => 4500,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 15,
                'payment_process' => 'instant',
                'settlement' => 0,
            ],
            [
                'name' => 'Bank Permata',
                'code' => 'PERMATA',
                'type' => 'VIRTUAL_ACCOUNT',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'VA/PERMATA.png',
                'action' => 'account',
                'min' => 10000,
                'max' => 999999999,
                'fee_type_1' => 'amount',
                'fee_value_1' => 4500,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 15,
                'payment_process' => 'instant',
                'settlement' => 0,
            ],
            [
                'name' => 'Bank Sahabat Sampoerna',
                'code' => 'BSS',
                'type' => 'VIRTUAL_ACCOUNT',
                'reference' => null,
                'status' => false,
                'source' => 'xendit',
                'image' => 'VA/BSS.png',
                'action' => 'account',
                'min' => 10000,
                'max' => 5000000000,
                'fee_type_1' => 'amount',
                'fee_value_1' => 4500,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 15,
                'payment_process' => 'instant',
                'settlement' => 0,
            ],
            [
                'name' => 'Bank Jawa Barat',
                'code' => 'BJB',
                'type' => 'VIRTUAL_ACCOUNT',
                'reference' => null,
                'status' => true,
                'source' => 'xendit',
                'image' => 'VA/BJB.png',
                'action' => 'account',
                'min' => 10000,
                'max' => 500000000,
                'fee_type_1' => 'amount',
                'fee_value_1' => 4500,
                'fee_type_2' => null,
                'fee_value_2' => null,
                'is_ppn' => true,
                'expired' => 15,
                'payment_process' => 'instant',
                'settlement' => 0,
            ]

    ];

    return $dataPayments;
    }
}
